In [1]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

# Matrix Multiplication
matrix_mult = np.dot(matrix_a, matrix_b)  # or matrix_mult = matrix_a @ matrix_b
print("Matrix Multiplication:")
print(matrix_mult)

# Element-wise Multiplication
elementwise_mult = matrix_a * matrix_b
print("\nElement-wise Multiplication:")
print(elementwise_mult)


Matrix Multiplication:
[[19 22]
 [43 50]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]


In [2]:
import numpy as np

# Create a multi-dimensional array
multi_dim_array = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

# Using ravel()
flattened_ravel = multi_dim_array.ravel()
print("Flattened using ravel():")
print(flattened_ravel)

# Using flatten()
flattened_flatten = multi_dim_array.flatten()
print("\nFlattened using flatten():")
print(flattened_flatten)


Flattened using ravel():
[1 2 3 4 5 6 7 8 9]

Flattened using flatten():
[1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array
array_2d = array_1d.reshape(2, 3)
print("Reshaped 2D array:")
print(array_2d)

# Reshape the 2D array back into a 1D array
reshaped_back = array_2d.reshape(-1)  # -1 means automatically compute the size along that dimension
print("\nReshaped back to 1D array:")
print(reshaped_back)


Reshaped 2D array:
[[1 2 3]
 [4 5 6]]

Reshaped back to 1D array:
[1 2 3 4 5 6]


In [7]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3])

# Compute element-wise exponential
exp_arr = np.exp(arr)
print("Exponential:")
print(exp_arr)


# Compute element-wise natural logarithm
log_arr = np.log(exp_arr)
print("\nNatural Logarithm:")
print(log_arr)


# Compute element-wise base-10 logarithm
log10_arr = np.log10(exp_arr)
print("\nBase-10 Logarithm:")
print(log10_arr)





Exponential:
[ 2.71828183  7.3890561  20.08553692]

Natural Logarithm:
[1. 2. 3.]

Base-10 Logarithm:
[0.43429448 0.86858896 1.30288345]


In [8]:
import numpy as np

# Create an array
arr = np.array([12, 5, 23, 8, 19, 3])

# Find the maximum and minimum elements
max_value = np.max(arr)
min_value = np.min(arr)

print("Array:", arr)
print("Maximum:", max_value)
print("Minimum:", min_value)


Array: [12  5 23  8 19  3]
Maximum: 23
Minimum: 3
